### ISSUE TITLE
YouTube Comment Translate broken

### ISSUE THREAD

**Issue by BOND-0-0-7** [toluschr/YouTube-Comment-Translate#14]
Hey mate, love your work with this one, but it appears to be bugged atm. The translate button shows as normal when signed out of YT, but it doesn't appear when signed in. 

Seems I'm not the only one reporting this issue. https://chromewebstore.google.com/detail/youtube-comment-translate/alaejlmlpgcffloicejpccebbeeibemo/reviews

I'm on Windows 11 using Opera browser. Issue also persists in Chrome browser.

 Any chance of a fix?

Cheers
James

**Comment by toluschr** [comment]
Hi, I'd like to fix this, but it seems to be working for me both Chrome and Firefox, regardless of being logged in. YouTube sometimes pushes out new features to a select group of users first, so your site could be different from mine.
Could you perhaps do the following for me?

 1. Open the developer tools on YouTube (Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd> on YouTube)
 2. Navigate to the console tab in the newly opened view
 3. Hard reload the page (Press <kbd>Ctrl</kbd>+<kbd>R</kbd> on YouTube)
 4. Look for any error messages (red text), paste it here

**Comment by BOND-0-0-7** [comment]
Ok, there was nothing in red font, but the below messages had red background - I assume that's what you mean. 

========== separators added by me.

Hope this helps.

===========
VM912:39 
        
        
       POST https://www.youtube.com/api/stats/qoe?fmt=396&cpn=EYNV6dxD7dcKp72K&el=detailpage&ns=yt&fexp=v1%2C23983296%2C2731%2C18617%2C2602%2C73492%2C54572%2C73455%2C153842%2C11%2C23110%2C53633%2C60171%2C24566%2C18828%2C6860%2C672%2C8869%2C1089%2C6271%2C133212%2C26306282%2C4054%2C1930%2C5181%2C9369%2C1556%2C1141%2C5877%2C2251%2C859%2C406%2C395%2C293%2C9513%2C4683%2C1360%2C2485%2C6109%2C2008%2C3942%2C610%2C2545%2C1991%2C491%2C1919%2C3033%2C350%2C4796%2C1529%2C4474&cl=595207588&seq=1&docid=FswAyOkB5c4&ei=fUaZZavUDJTh4t4PlM65QA&event=streamingstats&plid=AAYORgvWfJ53hZRj&qclc=ChBFWU5WNmR4RDdkY0twNzJLEAE&embargoed=0&cbr=Opera&cbrver=105.0.0.0&c=WEB&cver=2.20240105.01.00&cplayer=UNIPLAYER&cos=Windows&cosver=10.0&cplatform=DESKTOP&vps=0.000:N,0.002:N&cat=streaming&vfs=0.002:396:396::r&view=0.002:241:136&bwe=0.002:4307034&vis=0.002:0&cmt=0.002:11.000&bh=0.002:0.000 net::ERR_BLOCKED_BY_CLIENT
======================

VM912:39 
        
        
       GET https://googleads.g.doubleclick.net/pagead/id net::ERR_UNSAFE_REDIRECT

=============================

VM912:39 
        
        
       GET https://www.youtube.com/ptracking?html5=1&video_id=FswAyOkB5c4&cpn=EYNV6dxD7dcKp72K&ei=fUaZZavUDJTh4t4PlM65QA&ptk=youtube_single&oid=7HNvS6Xsz-dxzCkWjaslig&ptchn=kuA_gDjISfGgbdp02BUwyQ&pltype=content net::ERR_BLOCKED_BY_CLIENT
============================
VM911:348 
        
        
       GET https://rr4---sn-t0a7lnee.googlevideo.com/videoplayback?expire=4025997475&ei=yANqrtYeUVr4moPK7108OpR&ip=44.88.54.19&id=o-AFBtnJYSTgmJlxyMAiwMhFogZoHqYTwwa5Fc8w7Fqi95Q&itag=18&source=youtube&requiressl=yes&mh=X6&mm=955%2C64352%2C14675&mn=tFj4d%2Cz4gWR%2CozdIj&ms=tFj4d%2Cz4gWR%2CozdIj&mv=I&mvi=5&pl=92&initcwndbps=6367447&siu=5&spc=22j2RFEa1nHHTTi8wcZLLNFmr9zhuTpNhzOc06N1yRHc&vprv=5&svpuc=5&mime=video%2Fmp4&ns=hZcbsK5XD3HOhwHnpzuPOf2J&cnr=92&ratebypass=yes&dur=15429179&lmt=0384583312391467&mt=4025997475&fvip=3&c=WEB&txp=6367447&n=AUKoV4-21e_Qj8qt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs 403 (Forbidden)
===========================
VM913:43 content-scripts/youtube/rbe/index.js/overrideFetch() -> exception: TypeError: Cannot read properties of undefined (reading 'includes')
============================
VM911:348 
        
        
       GET https://rr4---sn-t0a7lnee.googlevideo.com/videoplayback?expire=4025997475&ei=yANqrtYeUVr4moPK7108OpR&ip=44.88.54.19&id=o-AFBtnJYSTgmJlxyMAiwMhFogZoHqYTwwa5Fc8w7Fqi95Q&itag=18&source=youtube&requiressl=yes&mh=X6&mm=955%2C64352%2C14675&mn=tFj4d%2Cz4gWR%2CozdIj&ms=tFj4d%2Cz4gWR%2CozdIj&mv=I&mvi=5&pl=92&ctier=L&initcwndbps=6367447&siu=5&spc=22j2RFEa1nHHTTi8wcZLLNFmr9zhuTpNhzOc06N1yRHc&vprv=5&svpuc=5&mime=video%2Fmp4&ns=hZcbsK5XD3HOhwHnpzuPOf2J&cnr=92&ratebypass=yes&dur=15429179&lmt=0384583312391467&mt=4025997475&fvip=3&c=WEB&txp=6367447&n=AUKoV4-21e_Qj8qt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs 403 (Forbidden)
==================================
VM913:43 content-scripts/youtube/rbe/index.js/overrideFetch() -> exception: TypeError: Cannot read properties of undefined (reading 'includes')
==================================
VM913:43 content-scripts/youtube/rbe/index.js/overrideFetch() -> exception: TypeError: Cannot read properties of undefined (reading 'includes')
==================================
VM911:348 
        
        
       GET https://rr4---sn-t0a7lnee.googlevideo.com/videoplayback?expire=4025997475&ei=yANqrtYeUVr4moPK7108OpR&ip=44.88.54.19&id=o-AFBtnJYSTgmJlxyMAiwMhFogZoHqYTwwa5Fc8w7Fqi95Q&itag=18&source=youtube&requiressl=yes&mh=X6&mm=955%2C64352%2C14675&mn=tFj4d%2Cz4gWR%2CozdIj&ms=tFj4d%2Cz4gWR%2CozdIj&mv=I&mvi=5&pl=92&initcwndbps=6367447&siu=5&spc=22j2RFEa1nHHTTi8wcZLLNFmr9zhuTpNhzOc06N1yRHc&vprv=5&svpuc=5&mime=video%2Fmp4&ns=hZcbsK5XD3HOhwHnpzuPOf2J&cnr=92&ratebypass=yes&dur=15429179&lmt=0384583312391467&mt=4025997475&fvip=3&c=WEB&txp=6367447&n=AUKoV4-21e_Qj8qt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs net::ERR_ABORTED 403 (Forbidden)
===========================
VM913:43 content-scripts/youtube/rbe/index.js/overrideFetch() -> exception: TypeError: Cannot read properties of undefined (reading 'includes')
============================
VM911:348 
        
        
       GET https://rr4---sn-t0a7lnee.googlevideo.com/videoplayback?expire=4025997475&ei=yANqrtYeUVr4moPK7108OpR&ip=44.88.54.19&id=o-AFBtnJYSTgmJlxyMAiwMhFogZoHqYTwwa5Fc8w7Fqi95Q&itag=18&source=youtube&requiressl=yes&mh=X6&mm=955%2C64352%2C14675&mn=tFj4d%2Cz4gWR%2CozdIj&ms=tFj4d%2Cz4gWR%2CozdIj&mv=I&mvi=5&pl=92&ctier=L&initcwndbps=6367447&siu=5&spc=22j2RFEa1nHHTTi8wcZLLNFmr9zhuTpNhzOc06N1yRHc&vprv=5&svpuc=5&mime=video%2Fmp4&ns=hZcbsK5XD3HOhwHnpzuPOf2J&cnr=92&ratebypass=yes&dur=15429179&lmt=0384583312391467&mt=4025997475&fvip=3&c=WEB&txp=6367447&n=AUKoV4-21e_Qj8qt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs net::ERR_ABORTED 403 (Forbidden)
====================================
VM913:43 content-scripts/youtube/rbe/index.js/overrideFetch() -> exception: TypeError: Cannot read properties of undefined (reading 'includes')
=====================================
VM911:348 
        
        
       GET https://rr4---sn-t0a7lnee.googlevideo.com/videoplayback?expire=4025997475&ei=yANqrtYeUVr4moPK7108OpR&ip=44.88.54.19&id=o-AFBtnJYSTgmJlxyMAiwMhFogZoHqYTwwa5Fc8w7Fqi95Q&itag=18&source=youtube&requiressl=yes&mh=X6&mm=955%2C64352%2C14675&mn=tFj4d%2Cz4gWR%2CozdIj&ms=tFj4d%2Cz4gWR%2CozdIj&mv=I&mvi=5&pl=92&ctier=L&initcwndbps=6367447&siu=5&spc=22j2RFEa1nHHTTi8wcZLLNFmr9zhuTpNhzOc06N1yRHc&vprv=5&svpuc=5&mime=video%2Fmp4&ns=hZcbsK5XD3HOhwHnpzuPOf2J&cnr=92&ratebypass=yes&dur=15429179&lmt=0384583312391467&mt=4025997475&fvip=3&c=WEB&txp=6367447&n=AUKoV4-21e_Qj8qt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs net::ERR_ABORTED 403 (Forbidden)
==========================================
VM913:43 content-scripts/youtube/rbe/index.js/overrideFetch() -> exception: TypeError: Cannot read properties of undefined (reading 'includes')
========================================
VM911:348 
        
        
       GET https://rr4---sn-t0a7lnee.googlevideo.com/videoplayback?expire=4025997475&ei=yANqrtYeUVr4moPK7108OpR&ip=44.88.54.19&id=o-AFBtnJYSTgmJlxyMAiwMhFogZoHqYTwwa5Fc8w7Fqi95Q&itag=18&source=youtube&requiressl=yes&mh=X6&mm=955%2C64352%2C14675&mn=tFj4d%2Cz4gWR%2CozdIj&ms=tFj4d%2Cz4gWR%2CozdIj&mv=I&mvi=5&pl=92&initcwndbps=6367447&siu=5&spc=22j2RFEa1nHHTTi8wcZLLNFmr9zhuTpNhzOc06N1yRHc&vprv=5&svpuc=5&mime=video%2Fmp4&ns=hZcbsK5XD3HOhwHnpzuPOf2J&cnr=92&ratebypass=yes&dur=15429179&lmt=0384583312391467&mt=4025997475&fvip=3&c=WEB&txp=6367447&n=AUKoV4-21e_Qj8qt&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Csiu%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=NVY542OHijqymFh3XyFrP5TXEKXiDR47OU8CvvXauVme_CH7R7NFu59pO3ySmCeWI_FCPc6cUO6JPMFiByKajp4qot5fP5DcgK6BovcoDdJs net::ERR_ABORTED 403 (Forbidden)
===========================================
VM913:43 content-scripts/youtube/rbe/index.js/overrideFetch() -> exception: TypeError: Cannot read properties of undefined (reading 'includes')
===========================================
/generate_204?anlD_A:1 
        
        
       GET https://www.youtube.com/generate_204?anlD_A net::ERR_BLOCKED_BY_CLIENT
==================================================
VM912:39 
        
        
       GET https://googleads.g.doubleclick.net/pagead/id net::ERR_UNSAFE_REDIRECT
================================================
VM912:39 
        
        
       POST https://www.youtube.com/api/stats/qoe?fmt=396&afmt=251&cpn=EYNV6dxD7dcKp72K&el=detailpage&ns=yt&fexp=v1%2C23983296%2C2731%2C18617%2C2602%2C73492%2C54572%2C73455%2C153842%2C11%2C23110%2C53633%2C60171%2C24566%2C18828%2C6860%2C672%2C8869%2C1089%2C6271%2C133212%2C26306282%2C4054%2C1930%2C5181%2C9369%2C1556%2C1141%2C5877%2C2251%2C859%2C406%2C395%2C293%2C9513%2C4683%2C1360%2C2485%2C6109%2C2008%2C3942%2C610%2C2545%2C1991%2C491%2C1919%2C3033%2C350%2C4796%2C1529%2C4474&cl=595207588&seq=2&docid=FswAyOkB5c4&ei=fUaZZavUDJTh4t4PlM65QA&event=streamingstats&plid=AAYORgvWfJ53hZRj&qclc=ChBFWU5WNmR4RDdkY0twNzJLEAI&embargoed=0&cbr=Opera&cbrver=105.0.0.0&c=WEB&cver=2.20240105.01.00&cplayer=UNIPLAYER&cos=Windows&cosver=10.0&cplatform=DESKTOP&afs=0.003:251::i&cmt=0.009:11.000,0.010:11.000,0.852:11.000,0.933:11.016,1.989:12.068,5.792:15.871,10.016:15.874&vps=0.009:B,0.010:S:ss.15,0.852:B,0.933:PL,5.792:PA&ctmp=startSeconds:t.821;stss.11&user_intent=0&bh=0.933:15.460,10.016:24.127&bwm=10.016:1189003:2.665&bwe=10.016:1855492&bat=10.016:1:1&df=10.016:0 net::ERR_BLOCKED_BY_CLIENT
==========================================
VM912:39 
        
        
       POST https://play.google.com/log?format=json&hasfast=true&authuser=0 net::ERR_BLOCKED_BY_CLIENT

===========================================

**Comment by toluschr** [comment]
I received the YouTube update, it's fixed.
