### ISSUE TITLE
translate in one line

### ISSUE THREAD

**Issue by Dark3n89** [toluschr/YouTube-Comment-Translate#5]
Hi, if you translate something with many lines, translated text jump to one long line and is out of window :/  Exist any fix for this?

**Comment by Dark3n89** [comment]
> @Dark3n89 I have the same issue. I don't know anything about JS and certainly there is better solution for this but I've found that inserting line `tb._ntext.style = "white-space: pre-wrap";` after line `tb._ntext = document.createElement("div");` brings script's behaviour back as it was before issue. Hope this helps.

Thanks this helped :)
![image](https://user-images.githubusercontent.com/48175529/179466728-abe1d5c2-b1fc-4baf-93c5-442f2310855b.png)

**Comment by toluschr** [comment]
Thanks and sorry for the delay
