### ISSUE TITLE
Can detect lang automatic by one line change :)

### ISSUE THREAD

**Issue by Dark3n89** [toluschr/YouTube-Comment-Translate#6]
add:
`var userLang = navigator.language || navigator.userLanguage;
`

and change line from:
`	var TRANSLATE_TEXT = "translate", UNDO_TEXT = "undo", TARGET = "en";
`
TO
`    var TRANSLATE_TEXT = " translate", UNDO_TEXT = " undo ", TARGET = userLang;
`

This will detect local browser lang and automatic translate to your language :)

Thank you for your code :)

**Comment by toluschr** [comment]
Should have worked like this in the first place. Thanks for the contribution.
