### ISSUE TITLE
Support for "Read Comments While Watching Video" feature

### ISSUE THREAD

**Issue by Pickles404** [toluschr/YouTube-Comment-Translate#7]
Hello, I really like the extension. Simple and fully functional. YouTube recently added a feature that allows you to read comments while watching the video, but unfortunately the extension does not work on it. I would like to know if it is possible to make it work with the feature enabled. thanks :)

**Comment by toluschr** [comment]
Thanks for opening the issue, it should now also work for the other comments section.

**Comment by Pickles404** [comment]
Thank you very much

**Comment by Pickles404** [comment]
Thank you so much :)
